// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:darts_with_friends/apikey.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String apikey = FB_api_key.apiKey;
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: apikey, //ne zaboraviti uzeti novi api key ako sam na drugom PC
    appId: '1:364148159176:web:c1f6c4cf922f429d466bfd',
    messagingSenderId: '364148159176',
    projectId: 'darts-with-friends',
    authDomain: 'darts-with-friends.firebaseapp.com',
    storageBucket: 'darts-with-friends.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: apikey,
    appId: '1:364148159176:android:4bfccf52f9eff2ee466bfd',
    messagingSenderId: '364148159176',
    projectId: 'darts-with-friends',
    storageBucket: 'darts-with-friends.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: apikey,
    appId: '1:364148159176:ios:11e92f3dbb75d459466bfd',
    messagingSenderId: '364148159176',
    projectId: 'darts-with-friends',
    storageBucket: 'darts-with-friends.appspot.com',
    iosBundleId: 'com.example.dartsWithFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: apikey,
    appId: '1:364148159176:ios:11e92f3dbb75d459466bfd',
    messagingSenderId: '364148159176',
    projectId: 'darts-with-friends',
    storageBucket: 'darts-with-friends.appspot.com',
    iosBundleId: 'com.example.dartsWithFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: apikey,
    appId: '1:364148159176:web:522597a8480bef8e466bfd',
    messagingSenderId: '364148159176',
    projectId: 'darts-with-friends',
    authDomain: 'darts-with-friends.firebaseapp.com',
    storageBucket: 'darts-with-friends.appspot.com',
  );
}
